version: '3'
services:

  nginx:
    image: nginx:1.19
    restart: unless-stopped
    volumes:
      - ../:/var/www:delegated
      - ./local.web.default.conf:/etc/nginx/conf.d/default.conf:delegated
    ports:
      - 8000:80
